PREFIX tw:    <http://tw.rpi.edu/schema/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DESCRIBE ?publication ?mostSpecificType ?topic ?research ?role ?author ?pub ?project ?publisher ?event
WHERE {
  ?publication a ?mostSpecificType .
  ?publication tw:hasAgentWithRole ?role .
  ?author tw:hasRole ?role .
  ?author a foaf:Person .
  OPTIONAL { ?publication tw:hasTopic ?topic }
  OPTIONAL { ?publication tw:hasThemeReference ?research }
  OPTIONAL { ?publication tw:inPublication ?pub }
  OPTIONAL { ?publication tw:hasProjectReference ?project }
  OPTIONAL { ?publication dct:publisher ?publisher }
  OPTIONAL { ?publication tw:inEvent ?event }
}
